spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/quizdev_testing
    username: quizuser
    password: quizpass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration

jwt:
  secret: "UpHXYn6W8RyDJFlb1F9grIoDw87uKo7wLRUhz8xgBrTrVm8Z5e3cc8d3kbsA2QabXElRI9koWkRGhxHy0WBclQ=="