spring:
  application:
    name: quizdev-api
  datasource:
    url: jdbc:postgresql://localhost:5432/quizdb
    username: quizuser
    password: quizpass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    url: jdbc:postgresql://localhost:5432/quizdb
    user: quizuser
    password: quizpass
    baseline-on-migrate: true
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080