spring:
  application:
    name: quizdev-api
  datasource:
    url: jdbc:postgresql://localhost:5432/quizdb
    username: quizuser
    password: quizpass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    url: jdbc:postgresql://localhost:5432/quizdb
    user: quizuser
    password: quizpass
    baseline-on-migrate: true
    enabled: true
    locations: classpath:db/migration

  security:
    user:
      name: dev
      password: "{noop}dev123"

management:
  endpoints:
    web:
      exposure:
        include: mappings

jwt:
  secret: "UpHXYn6W8RyDJFlb1F9grIoDw87uKo7wLRUhz8xgBrTrVm8Z5e3cc8d3kbsA2QabXElRI9koWkRGhxHy0WBclQ=="

server:
  port: 8080